[package]
name = "tiny_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
vulkano = "0.22.0"
vulkano-win = "0.22.0"
vulkano-shaders = "0.22.0"
winit = "0.24.0"
