[package]
name = "tiny_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
egui = "0.19.0"
eframe = "0.19.0"
yew = "0.19.3"
