[package]
name = "tiny_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
bevy = "0.9.1"
glam = "0.22.0"
